name: my_library_project
description: A library management system in Dart
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ^0.13.6
  json_annotation: ^4.5.0
  path: ^1.8.0
dev_dependencies:
  test: ^1.16.0
# Only for Flutter projects


